apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: db-password-secret
spec:
    secretStoreRef:
        name: aws-secret-store # Use the SecretStore we just defined
        kind: SecretStore
    target:
    # This is the name of the regular Kubernetes Secret that ESO will create.
    name: db-credentials
    creationPolicy: Owner
    data:
    - secretKey: password # The key inside the k8s Secret (e.g., data.password)
    remoteRef:
        key: guestbook/db-password # The name of the secret in AWS Secrets Manager