apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: aws-secret-store
spec:
    provider:
        aws:
        service: SecretsManager
        # The region where our secret lives.
        region: {{ .Values.aws.region | default "us-east-1" }}
        role: {{ .Values.aws.serviceAccountRoleArn }}